version: '0.0.1'
services:
  api:
    restart: always
    build:
      context: .
    depends_on:
      - mongodb
    ports:
      - 80:80
    networks:
      - database

  # MongoDB Database
  mongodb:
    image: mongo:4.4
    ports:
      - '27017:27017'
    networks:
      - database

networks:
  database:
    driver: bridge
